//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uling_RestaurantManagementSystem.Models.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_urmsEntities : DbContext
    {
        public db_urmsEntities()
            : base("name=db_urmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_discounts> tbl_discounts { get; set; }
        public virtual DbSet<tbl_menu_items> tbl_menu_items { get; set; }
        public virtual DbSet<tbl_order_items> tbl_order_items { get; set; }
        public virtual DbSet<tbl_orders> tbl_orders { get; set; }
        public virtual DbSet<tbl_payment> tbl_payment { get; set; }
        public virtual DbSet<tbl_receipts> tbl_receipts { get; set; }
        public virtual DbSet<tbl_reservations> tbl_reservations { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
    }
}
