//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uling_RestaurantManagementSystem.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_discounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_discounts()
        {
            this.tbl_order_items = new HashSet<tbl_order_items>();
        }
    
        public int discount_id { get; set; }
        public string discount_code { get; set; }
        public string description { get; set; }
        public decimal discount_percentage { get; set; }
        public decimal discount_amount { get; set; }
        public Nullable<int> is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_items> tbl_order_items { get; set; }
    }
}
