//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uling_RestaurantManagementSystem.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reservations
    {
        public int reservation_id { get; set; }
        public int order_id { get; set; }
        public System.DateTime reservation_date { get; set; }
        public System.TimeSpan time_start { get; set; }
        public System.TimeSpan time_end { get; set; }
        public int heads { get; set; }
        public string note { get; set; }
        public string reservation_status { get; set; }
    
        public virtual tbl_orders tbl_orders { get; set; }
    }
}
