//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uling_RestaurantManagementSystem.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order_items
    {
        public int order_item_id { get; set; }
        public int order_id { get; set; }
        public int menu_item_id { get; set; }
        public int quantity { get; set; }
        public decimal line_price { get; set; }
        public Nullable<int> discount_id { get; set; }
    
        public virtual tbl_discounts tbl_discounts { get; set; }
        public virtual tbl_menu_items tbl_menu_items { get; set; }
        public virtual tbl_orders tbl_orders { get; set; }
    }
}
