//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uling_RestaurantManagementSystem.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_orders()
        {
            this.tbl_order_items = new HashSet<tbl_order_items>();
            this.tbl_reservations = new HashSet<tbl_reservations>();
            this.tbl_payment = new HashSet<tbl_payment>();
            this.tbl_receipts = new HashSet<tbl_receipts>();
        }
    
        public int order_id { get; set; }
        public string order_type { get; set; }
        public decimal total_amount { get; set; }
        public System.DateTime date_ordered { get; set; }
        public string customer_name { get; set; }
        public string email { get; set; }
        public string contact_number { get; set; }
        public string order_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_items> tbl_order_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_reservations> tbl_reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_payment> tbl_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_receipts> tbl_receipts { get; set; }
    }
}
