//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uling_RestaurantManagementSystem.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment
    {
        public int payment_id { get; set; }
        public int order_id { get; set; }
        public decimal amount { get; set; }
        public string payment_method { get; set; }
        public string payment_url { get; set; }
        public string payment_status { get; set; }
    
        public virtual tbl_orders tbl_orders { get; set; }
    }
}
