//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uling_RestaurantManagementSystem.Models.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_receipts
    {
        public int receipt_id { get; set; }
        public int order_id { get; set; }
        public System.DateTime receipt_date { get; set; }
        public decimal sub_total { get; set; }
        public decimal amount_due { get; set; }
        public int cashier_id { get; set; }
    
        public virtual tbl_orders tbl_orders { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
